const initialDeck1 = [
    {
        id: "Blue 1.0",
        level: 1,
        color: "blue",
        redPrice: 1,
        greenPrice: 1,
        bluePrice: 0,
        yellowPrice: 1,
        whitePrice: 1,
        points: 0,
    },
    {
        id: "Blue 1.1",
        level: 1,
        color: "blue",
        redPrice: 2,
        greenPrice: 1,
        bluePrice: 0,
        yellowPrice: 1,
        whitePrice: 1,
        points: 0,
    },
    {
        id: "Blue 1.2",
        level: 1,
        color: "blue",
        redPrice: 2,
        greenPrice: 2,
        bluePrice: 0,
        yellowPrice: 0,
        whitePrice: 1,
        points: 0,
    },
    {
        id: "Blue 1.3",
        level: 1,
        color: "blue",
        redPrice: 1,
        greenPrice: 3,
        bluePrice: 1,
        yellowPrice: 0,
        whitePrice: 0,
        points: 0,
    },
    {
        id: "Blue 1.4",
        level: 1,
        color: "blue",
        redPrice: 0,
        greenPrice: 0,
        bluePrice: 0,
        yellowPrice: 2,
        whitePrice: 1,
        points: 0,
    },
    {
        id: "Blue 1.5",
        level: 1,
        color: "blue",
        redPrice: 0,
        greenPrice: 2,
        bluePrice: 0,
        yellowPrice: 2,
        whitePrice: 0,
        points: 0,
    },
    {
        id: "Blue 1.6",
        level: 1,
        color: "blue",
        redPrice: 0,
        greenPrice: 0,
        bluePrice: 0,
        yellowPrice: 3,
        whitePrice: 0,
        points: 0,
    },
];

const initialDeck2 = [
    {
        id: "Blue 2.0",
        level: 2,
        color: "blue",
        redPrice: 1,
        greenPrice: 1,
        bluePrice: 0,
        yellowPrice: 1,
        whitePrice: 1,
        points: 0,
    },
    // Add more cards here...
];

const initialDeck3 = [
    {
        id: "Blue 3.0",
        level: 3,
        color: "blue",
        redPrice: 3,
        greenPrice: 3,
        bluePrice: 0,
        yellowPrice: 5,
        whitePrice: 3,
        points: 3,
    },
    {
        id: "Blue 3.1",
        level: 3,
        color: "blue",
        redPrice: 0,
        greenPrice: 0,
        bluePrice: 0,
        yellowPrice: 0,
        whitePrice: 7,
        points: 4,
    },
    {
        id: "Blue 3.2",
        level: 3,
        color: "blue",
        redPrice: 0,
        greenPrice: 0,
        bluePrice: 3,
        yellowPrice: 3,
        whitePrice: 6,
        points: 4,
    },
    {
        id: "Blue 3.3",
        level: 3,
        color: "blue",
        redPrice: 0,
        greenPrice: 0,
        bluePrice: 3,
        yellowPrice: 0,
        whitePrice: 7,
        points: 5,
    },
    {
        id: "Green 3.0",
        level: 3,
        color: "green",
        redPrice: 3,
        greenPrice: 0,
        bluePrice: 3,
        yellowPrice: 3,
        whitePrice: 5,
        points: 3,
    },
    {
        id: "Green 3.1",
        level: 3,
        color: "green",
        redPrice: 0,
        greenPrice: 0,
        bluePrice: 7,
        yellowPrice: 0,
        whitePrice: 0,
        points: 4,
    },
    {
        id: "Green 3.2",
        level: 3,
        color: "green",
        redPrice: 0,
        greenPrice: 3,
        bluePrice: 6,
        yellowPrice: 0,
        whitePrice: 3,
        points: 4,
    },
    {
        id: "Green 3.3",
        level: 3,
        color: "green",
        redPrice: 0,
        greenPrice: 3,
        bluePrice: 7,
        yellowPrice: 0,
        whitePrice: 0,
        points: 5,
    },
    {
        id: "Red 3.0",
        level: 3,
        color: "red",
        redPrice: 0,
        greenPrice: 3,
        bluePrice: 5,
        yellowPrice: 3,
        whitePrice: 3,
        points: 3,
    },
    {
        id: "Red 3.1",
        level: 3,
        color: "red",
        redPrice: 0,
        greenPrice: 7,
        bluePrice: 0,
        yellowPrice: 0,
        whitePrice: 0,
        points: 4,
    },
    {
        id: "Red 3.2",
        level: 3,
        color: "red",
        redPrice: 3,
        greenPrice: 6,
        bluePrice: 3,
        yellowPrice: 0,
        whitePrice: 0,
        points: 4,
    },
    {
        id: "Red 3.3",
        level: 3,
        color: "red",
        redPrice: 3,
        greenPrice: 7,
        bluePrice: 0,
        yellowPrice: 0,
        whitePrice: 0,
        points: 5,
    },
    {
        id: "White 3.0",
        level: 3,
        color: "white",
        redPrice: 5,
        greenPrice: 3,
        bluePrice: 3,
        yellowPrice: 3,
        whitePrice: 0,
        points: 3,
    },
    {
        id: "White 3.1",
        level: 3,
        color: "white",
        redPrice: 0,
        greenPrice: 0,
        bluePrice: 0,
        yellowPrice: 7,
        whitePrice: 0,
        points: 4,
    },
    {
        id: "White 3.2",
        level: 3,
        color: "white",
        redPrice: 3,
        greenPrice: 0,
        bluePrice: 0,
        yellowPrice: 6,
        whitePrice: 3,
        points: 4,
    },
    {
        id: "White 3.3",
        level: 3,
        color: "white",
        redPrice: 0,
        greenPrice: 0,
        bluePrice: 0,
        yellowPrice: 7,
        whitePrice: 3,
        points: 5,
    },
    {
        id: "Yellow 3.0",
        level: 3,
        color: "yellow",
        redPrice: 1,
        greenPrice: 1,
        bluePrice: 1,
        yellowPrice: 0,
        whitePrice: 1,
        points: 3,
    },
    {
        id: "Yellow 3.1",
        level: 3,
        color: "yellow",
        redPrice: 1,
        greenPrice: 0,
        bluePrice: 0,
        yellowPrice: 0,
        whitePrice: 0,
        points: 4,
    },
    {
        id: "Yellow 3.2",
        level: 3,
        color: "yellow",
        redPrice: 1,
        greenPrice: 1,
        bluePrice: 0,
        yellowPrice: 1,
        whitePrice: 0,
        points: 4,
    },
    {
        id: "Yellow 3.0",
        level: 3,
        color: "yellow",
        redPrice: 1,
        greenPrice: 0,
        bluePrice: 0,
        yellowPrice: 1,
        whitePrice: 0,
        points: 5,
    },
];

export const shuffle = (deck) => {
    return [...deck].sort(() => Math.random() - 0.5);
};

export { initialDeck1, initialDeck2, initialDeck3 }