# --- Level-1 cards --------------------------------------------------
initial_deck1 = [
    {
        "id": "Blue 1.0",
        "level": 1,
        "color": "blue",
        "redPrice": 1,
        "greenPrice": 1,
        "bluePrice": 0,
        "yellowPrice": 1,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Blue 1.1",
        "level": 1,
        "color": "blue",
        "redPrice": 2,
        "greenPrice": 1,
        "bluePrice": 0,
        "yellowPrice": 1,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Blue 1.2",
        "level": 1,
        "color": "blue",
        "redPrice": 2,
        "greenPrice": 2,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Blue 1.3",
        "level": 1,
        "color": "blue",
        "redPrice": 1,
        "greenPrice": 3,
        "bluePrice": 1,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Blue 1.4",
        "level": 1,
        "color": "blue",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 2,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Blue 1.5",
        "level": 1,
        "color": "blue",
        "redPrice": 0,
        "greenPrice": 2,
        "bluePrice": 0,
        "yellowPrice": 2,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Blue 1.6",
        "level": 1,
        "color": "blue",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 3,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Blue 1.7",
        "level": 1,
        "color": "blue",
        "redPrice": 4,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Green 1.0",
        "level": 1,
        "color": "green",
        "redPrice": 1,
        "greenPrice": 0,
        "bluePrice": 1,
        "yellowPrice": 1,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Green 1.1",
        "level": 1,
        "color": "green",
        "redPrice": 1,
        "greenPrice": 0,
        "bluePrice": 1,
        "yellowPrice": 2,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Green 1.2",
        "level": 1,
        "color": "green",
        "redPrice": 2,
        "greenPrice": 0,
        "bluePrice": 1,
        "yellowPrice": 2,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Green 1.3",
        "level": 1,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 1,
        "bluePrice": 3,
        "yellowPrice": 0,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Green 1.4",
        "level": 1,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 1,
        "yellowPrice": 0,
        "whitePrice": 2,
        "points": 0,
    },
    {
        "id": "Green 1.5",
        "level": 1,
        "color": "green",
        "redPrice": 2,
        "greenPrice": 0,
        "bluePrice": 2,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Green 1.6",
        "level": 1,
        "color": "green",
        "redPrice": 3,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Green 1.7",
        "level": 1,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 4,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Red 1.0",
        "level": 1,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 1,
        "bluePrice": 1,
        "yellowPrice": 1,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Red 1.1",
        "level": 1,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 1,
        "bluePrice": 1,
        "yellowPrice": 1,
        "whitePrice": 2,
        "points": 0,
    },
    {
        "id": "Red 1.2",
        "level": 1,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 1,
        "bluePrice": 0,
        "yellowPrice": 2,
        "whitePrice": 2,
        "points": 0,
    },
    {
        "id": "Red 1.3",
        "level": 1,
        "color": "red",
        "redPrice": 1,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 3,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Red 1.4",
        "level": 1,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 1,
        "bluePrice": 2,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Red 1.5",
        "level": 1,
        "color": "red",
        "redPrice": 2,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 2,
        "points": 0,
    },
    {
        "id": "Red 1.6",
        "level": 1,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 3,
        "points": 0,
    },
    {
        "id": "Red 1.7",
        "level": 1,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 4,
        "points": 1,
    },
    {
        "id": "White 1.0",
        "level": 1,
        "color": "white",
        "redPrice": 1,
        "greenPrice": 1,
        "bluePrice": 1,
        "yellowPrice": 1,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "White 1.1",
        "level": 1,
        "color": "white",
        "redPrice": 1,
        "greenPrice": 2,
        "bluePrice": 1,
        "yellowPrice": 1,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "White 1.2",
        "level": 1,
        "color": "white",
        "redPrice": 0,
        "greenPrice": 2,
        "bluePrice": 2,
        "yellowPrice": 1,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "White 1.3",
        "level": 1,
        "color": "white",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 1,
        "yellowPrice": 1,
        "whitePrice": 3,
        "points": 0,
    },
    {
        "id": "White 1.4",
        "level": 1,
        "color": "white",
        "redPrice": 2,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 1,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "White 1.5",
        "level": 1,
        "color": "white",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 2,
        "yellowPrice": 2,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "White 1.6",
        "level": 1,
        "color": "white",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 3,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "White 1.7",
        "level": 1,
        "color": "white",
        "redPrice": 0,
        "greenPrice": 4,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 1,
    },
    {
        "id": "Yellow 1.0",
        "level": 1,
        "color": "yellow",
        "redPrice": 1,
        "greenPrice": 1,
        "bluePrice": 1,
        "yellowPrice": 0,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Yellow 1.1",
        "level": 1,
        "color": "yellow",
        "redPrice": 1,
        "greenPrice": 1,
        "bluePrice": 2,
        "yellowPrice": 0,
        "whitePrice": 1,
        "points": 0,
    },
    {
        "id": "Yellow 1.2",
        "level": 1,
        "color": "yellow",
        "redPrice": 1,
        "greenPrice": 0,
        "bluePrice": 2,
        "yellowPrice": 0,
        "whitePrice": 2,
        "points": 0,
    },
    {
        "id": "Yellow 1.3",
        "level": 1,
        "color": "yellow",
        "redPrice": 3,
        "greenPrice": 1,
        "bluePrice": 0,
        "yellowPrice": 1,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Yellow 1.4",
        "level": 1,
        "color": "yellow",
        "redPrice": 1,
        "greenPrice": 2,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Yellow 1.5",
        "level": 1,
        "color": "yellow",
        "redPrice": 0,
        "greenPrice": 2,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 2,
        "points": 0,
    },
    {
        "id": "Yellow 1.6",
        "level": 1,
        "color": "yellow",
        "redPrice": 0,
        "greenPrice": 3,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Yellow 1.7",
        "level": 1,
        "color": "yellow",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 4,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 1,
    },
]

# --- Level-2 cards --------------------------------------------------
initial_deck2 = [
    {
        "id": "Blue 2.0",
        "level": 2,
        "color": "blue",
        "redPrice": 3,
        "greenPrice": 2,
        "bluePrice": 2,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 0,
    },
    {
        "id": "Blue 2.1",
        "level": 2,
        "color": "blue",
        "redPrice": 0,
        "greenPrice": 3,
        "bluePrice": 2,
        "yellowPrice": 3,
        "whitePrice": 0,
        "points": 1,
    },
    {
        "id": "Blue 2.2",
        "level": 2,
        "color": "blue",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 3,
        "yellowPrice": 0,
        "whitePrice": 5,
        "points": 2,
    },
    {
        "id": "Blue 2.3",
        "level": 2,
        "color": "blue",
        "redPrice": 1,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 4,
        "whitePrice": 2,
        "points": 2,
    },
    {
        "id": "Blue 2.4",
        "level": 2,
        "color": "blue",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 5,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 2,
    },
    {
        "id": "Blue 2.5",
        "level": 2,
        "color": "blue",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 6,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 3,
    },
    {
        "id": "Green 2.0",
        "level": 2,
        "color": "green",
        "redPrice": 3,
        "greenPrice": 2,
        "bluePrice": 1,
        "yellowPrice": 2,
        "whitePrice": 3,
        "points": 1,
    },
    {
        "id": "Green 2.1",
        "level": 2,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 3,
        "yellowPrice": 2,
        "whitePrice": 2,
        "points": 1,
    },
    {
        "id": "Green 2.2",
        "level": 2,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 2,
        "yellowPrice": 1,
        "whitePrice": 4,
        "points": 2,
    },
    {
        "id": "Green 2.3",
        "level": 2,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 3,
        "bluePrice": 5,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 2,
    },
    {
        "id": "Green 2.4",
        "level": 2,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 5,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 2,
    },
    {
        "id": "Green 2.5",
        "level": 2,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 6,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 3,
    },
    {
        "id": "Red 2.0",
        "level": 2,
        "color": "red",
        "redPrice": 2,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 3,
        "whitePrice": 2,
        "points": 1,
    },
    {
        "id": "Red 2.1",
        "level": 2,
        "color": "red",
        "redPrice": 2,
        "greenPrice": 0,
        "bluePrice": 3,
        "yellowPrice": 3,
        "whitePrice": 0,
        "points": 1,
    },
    {
        "id": "Red 2.2",
        "level": 2,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 2,
        "bluePrice": 4,
        "yellowPrice": 0,
        "whitePrice": 1,
        "points": 2,
    },
    {
        "id": "Red 2.3",
        "level": 2,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 5,
        "whitePrice": 3,
        "points": 2,
    },
    {
        "id": "Red 2.4",
        "level": 2,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 5,
        "whitePrice": 0,
        "points": 2,
    },
    {
        "id": "Red 2.5",
        "level": 2,
        "color": "red",
        "redPrice": 6,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 3,
    },
    {
        "id": "White 2.0",
        "level": 2,
        "color": "white",
        "redPrice": 2,
        "greenPrice": 3,
        "bluePrice": 0,
        "yellowPrice": 2,
        "whitePrice": 0,
        "points": 1,
    },
    {
        "id": "White 2.1",
        "level": 2,
        "color": "white",
        "redPrice": 3,
        "greenPrice": 0,
        "bluePrice": 3,
        "yellowPrice": 0,
        "whitePrice": 2,
        "points": 1,
    },
    {
        "id": "White 2.2",
        "level": 2,
        "color": "white",
        "redPrice": 4,
        "greenPrice": 1,
        "bluePrice": 0,
        "yellowPrice": 2,
        "whitePrice": 0,
        "points": 2,
    },
    {
        "id": "White 2.3",
        "level": 2,
        "color": "white",
        "redPrice": 5,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 3,
        "whitePrice": 0,
        "points": 2,
    },
    {
        "id": "White 2.4",
        "level": 2,
        "color": "white",
        "redPrice": 5,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 2,
    },
    {
        "id": "White 2.5",
        "level": 2,
        "color": "white",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 6,
        "points": 3,
    },
    {
        "id": "Yellow 2.0",
        "level": 2,
        "color": "yellow",
        "redPrice": 0,
        "greenPrice": 2,
        "bluePrice": 2,
        "yellowPrice": 0,
        "whitePrice": 3,
        "points": 1,
    },
    {
        "id": "Yellow 2.1",
        "level": 2,
        "color": "yellow",
        "redPrice": 0,
        "greenPrice": 3,
        "bluePrice": 0,
        "yellowPrice": 2,
        "whitePrice": 3,
        "points": 1,
    },
    {
        "id": "Yellow 2.2",
        "level": 2,
        "color": "yellow",
        "redPrice": 2,
        "greenPrice": 4,
        "bluePrice": 1,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 2,
    },
    {
        "id": "Yellow 2.3",
        "level": 2,
        "color": "yellow",
        "redPrice": 3,
        "greenPrice": 5,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 2,
    },
    {
        "id": "Yellow 2.4",
        "level": 2,
        "color": "yellow",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 5,
        "points": 2,
    },
    {
        "id": "Yellow 2.5",
        "level": 2,
        "color": "yellow",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 6,
        "whitePrice": 0,
        "points": 3,
    },
]

# --- Level-3 cards --------------------------------------------------
initial_deck3 = [
    {
        "id": "Blue 3.0",
        "level": 3,
        "color": "blue",
        "redPrice": 3,
        "greenPrice": 3,
        "bluePrice": 0,
        "yellowPrice": 5,
        "whitePrice": 3,
        "points": 3,
    },
    {
        "id": "Blue 3.1",
        "level": 3,
        "color": "blue",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 7,
        "points": 4,
    },
    {
        "id": "Blue 3.2",
        "level": 3,
        "color": "blue",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 3,
        "yellowPrice": 3,
        "whitePrice": 6,
        "points": 4,
    },
    {
        "id": "Blue 3.3",
        "level": 3,
        "color": "blue",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 3,
        "yellowPrice": 0,
        "whitePrice": 7,
        "points": 5,
    },
    {
        "id": "Green 3.0",
        "level": 3,
        "color": "green",
        "redPrice": 3,
        "greenPrice": 0,
        "bluePrice": 3,
        "yellowPrice": 3,
        "whitePrice": 5,
        "points": 3,
    },
    {
        "id": "Green 3.1",
        "level": 3,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 7,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 4,
    },
    {
        "id": "Green 3.2",
        "level": 3,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 3,
        "bluePrice": 6,
        "yellowPrice": 0,
        "whitePrice": 3,
        "points": 4,
    },
    {
        "id": "Green 3.3",
        "level": 3,
        "color": "green",
        "redPrice": 0,
        "greenPrice": 3,
        "bluePrice": 7,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 5,
    },
    {
        "id": "Red 3.0",
        "level": 3,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 3,
        "bluePrice": 5,
        "yellowPrice": 3,
        "whitePrice": 3,
        "points": 3,
    },
    {
        "id": "Red 3.1",
        "level": 3,
        "color": "red",
        "redPrice": 0,
        "greenPrice": 7,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 4,
    },
    {
        "id": "Red 3.2",
        "level": 3,
        "color": "red",
        "redPrice": 3,
        "greenPrice": 6,
        "bluePrice": 3,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 4,
    },
    {
        "id": "Red 3.3",
        "level": 3,
        "color": "red",
        "redPrice": 3,
        "greenPrice": 7,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 5,
    },
    {
        "id": "White 3.0",
        "level": 3,
        "color": "white",
        "redPrice": 5,
        "greenPrice": 3,
        "bluePrice": 3,
        "yellowPrice": 3,
        "whitePrice": 0,
        "points": 3,
    },
    {
        "id": "White 3.1",
        "level": 3,
        "color": "white",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 7,
        "whitePrice": 0,
        "points": 4,
    },
    {
        "id": "White 3.2",
        "level": 3,
        "color": "white",
        "redPrice": 3,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 6,
        "whitePrice": 3,
        "points": 4,
    },
    {
        "id": "White 3.3",
        "level": 3,
        "color": "white",
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 7,
        "whitePrice": 3,
        "points": 5,
    },
    {
        "id": "Yellow 3.0",
        "level": 3,
        "color": "yellow",
        "redPrice": 1,
        "greenPrice": 1,
        "bluePrice": 1,
        "yellowPrice": 0,
        "whitePrice": 1,
        "points": 3,
    },
    {
        "id": "Yellow 3.1",
        "level": 3,
        "color": "yellow",
        "redPrice": 1,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 4,
    },
    {
        "id": "Yellow 3.2",
        "level": 3,
        "color": "yellow",
        "redPrice": 1,
        "greenPrice": 1,
        "bluePrice": 0,
        "yellowPrice": 1,
        "whitePrice": 0,
        "points": 4,
    },
    {
        "id": "Yellow 3.3",
        "level": 3,
        "color": "yellow",
        "redPrice": 1,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 1,
        "whitePrice": 0,
        "points": 5,
    },
]

# --- noble cards --------------------------------------------------
nobles = [
    {
        "id": "Noble 1",
        "level": None,
        "color": None,
        "redPrice": 0,
        "greenPrice": 4,
        "bluePrice": 4,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 3,
    },
    {
        "id": "Noble 2",
        "level": None,
        "color": None,
        "redPrice": 4,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 4,
        "whitePrice": 0,
        "points": 3,
    },
    {
        "id": "Noble 3",
        "level": None,
        "color": None,
        "redPrice": 3,
        "greenPrice": 3,
        "bluePrice": 3,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 3,
    },
    {
        "id": "Noble 4",
        "level": None,
        "color": None,
        "redPrice": 3,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 3,
        "whitePrice": 3,
        "points": 3,
    },
    {
        "id": "Noble 5",
        "level": None,
        "color": None,
        "redPrice": 3,
        "greenPrice": 3,
        "bluePrice": 0,
        "yellowPrice": 3,
        "whitePrice": 0,
        "points": 3,
    },
    {
        "id": "Noble 6",
        "level": None,
        "color": None,
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 4,
        "yellowPrice": 0,
        "whitePrice": 4,
        "points": 3,
    },
    {
        "id": "Noble 7",
        "level": None,
        "color": None,
        "redPrice": 4,
        "greenPrice": 4,
        "bluePrice": 0,
        "yellowPrice": 0,
        "whitePrice": 0,
        "points": 3,
    },
    {
        "id": "Noble 8",
        "level": None,
        "color": None,
        "redPrice": 0,
        "greenPrice": 3,
        "bluePrice": 3,
        "yellowPrice": 0,
        "whitePrice": 3,
        "points": 3,
    },
    {
        "id": "Noble 9",
        "level": None,
        "color": None,
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 3,
        "yellowPrice": 3,
        "whitePrice": 3,
        "points": 3,
    },
    {
        "id": "Noble 10",
        "level": None,
        "color": None,
        "redPrice": 0,
        "greenPrice": 0,
        "bluePrice": 0,
        "yellowPrice": 4,
        "whitePrice": 4,
        "points": 3,
    },
]